"""Class data for OSE Character Creator (Classic).

This module contains only data / static rules needed for Phase 1.
"""

CLASSES = {
    "Cleric": {
        "requirements": {},
        "prime_requisites": ["WIS"],
        "hit_die": 6,
        "max_level": 14,
        "armour": "Any (incl. shields)",
        "weapons": "Blunt only (club, mace, sling, staff, warhammer)",
        "languages": ["Alignment", "Common"],
        "saving_throws_lvl1": {"D": 11, "W": 12, "P": 14, "B": 16, "S": 15},
        "title_lvl1": "Acolyte",
        "xp_next_level": 1500,
        "special_abilities": [
            "Turn undead (2d6)",
            "Divine spells from 2nd level",
            "Cannot use edged or piercing weapons",
        ],
        "spellcaster": True,
        "spell_list": "cleric",
    },
    "Dwarf": {
        "requirements": {"CON": 9},
        "prime_requisites": ["STR"],
        "hit_die": 8,
        "max_level": 12,
        "armour": "Any (incl. shields)",
        "weapons": "Small/normal sized only (no longbow, no two-handed sword)",
        "languages": ["Alignment", "Common", "Dwarvish", "Gnomish", "Goblin", "Kobold"],
        "saving_throws_lvl1": {"D": 8, "W": 9, "P": 10, "B": 13, "S": 12},
        "title_lvl1": "Dwarven Veteran",
        "xp_next_level": 2200,
        "special_abilities": [
            "Infravision 60'",
            "Listen at doors 2-in-6",
            "Detect construction tricks 2-in-6",
            "Detect room traps 2-in-6",
        ],
        "spellcaster": False,
    },
    "Elf": {
        "requirements": {"INT": 9},
        "prime_requisites": ["INT", "STR"],
        "hit_die": 6,
        "max_level": 10,
        "armour": "Any (incl. shields)",
        "weapons": "Any",
        "languages": ["Alignment", "Common", "Elvish", "Gnoll", "Hobgoblin", "Orcish"],
        "saving_throws_lvl1": {"D": 12, "W": 13, "P": 13, "B": 15, "S": 15},
        "title_lvl1": "Medium",
        "xp_next_level": 4000,
        "special_abilities": [
            "Infravision 60'",
            "Listen at doors 2-in-6",
            "Detect secret doors 2-in-6 (when searching)",
            "Immune to ghoul paralysis",
            "Arcane spell book (1 spell at 1st level)",
        ],
        "spellcaster": True,
        "spell_list": "magic_user",  # elves use MU list
    },
    "Fighter": {
        "requirements": {},
        "prime_requisites": ["STR"],
        "hit_die": 8,
        "max_level": 14,
        "armour": "Any (incl. shields)",
        "weapons": "Any",
        "languages": ["Alignment", "Common"],
        "saving_throws_lvl1": {"D": 12, "W": 13, "P": 14, "B": 15, "S": 16},
        "title_lvl1": "Veteran",
        "xp_next_level": 2000,
        "special_abilities": [],
        "spellcaster": False,
    },
    "Halfling": {
        "requirements": {"CON": 9, "DEX": 9},
        "prime_requisites": ["DEX", "STR"],
        "hit_die": 6,
        "max_level": 8,
        "armour": "Any appropriate to size (incl. shields)",
        "weapons": "Any appropriate to size (no longbow, no two-handed sword)",
        "languages": ["Alignment", "Common", "Halfling"],
        "saving_throws_lvl1": {"D": 8, "W": 9, "P": 10, "B": 13, "S": 12},
        "title_lvl1": "Halfling Veteran",
        "xp_next_level": 2000,
        "special_abilities": [
            "Missile attack +1",
            "+2 AC vs large opponents",
            "Hide in woods 90%",
            "Hide in dungeons 2-in-6 (must be motionless)",
            "Listen at doors 2-in-6",
        ],
        "spellcaster": False,
    },
    "Magic-User": {
        "requirements": {},
        "prime_requisites": ["INT"],
        "hit_die": 4,
        "max_level": 14,
        "armour": "None",
        "weapons": "Dagger only",
        "languages": ["Alignment", "Common"],
        "saving_throws_lvl1": {"D": 13, "W": 14, "P": 13, "B": 16, "S": 15},
        "title_lvl1": "Medium",
        "xp_next_level": 2500,
        "special_abilities": [
            "Arcane spell book (1 spell at 1st level)",
        ],
        "spellcaster": True,
        "spell_list": "magic_user",
    },
    "Thief": {
        "requirements": {},
        "prime_requisites": ["DEX"],
        "hit_die": 4,
        "max_level": 14,
        "armour": "Leather only (no shields)",
        "weapons": "Any",
        "languages": ["Alignment", "Common"],
        "saving_throws_lvl1": {"D": 13, "W": 14, "P": 13, "B": 16, "S": 15},
        "title_lvl1": "Apprentice",
        "xp_next_level": 1200,
        "special_abilities": [
            "Back-stab (+4 to hit, double damage when attacking unaware from behind)",
            "Thief skills",
            "Cannot wear armour heavier than leather",
        ],
        "thief_skills_lvl1": {
            "CS": "87%",
            "TR": "10%",
            "HN": "1–2 on d6",
            "HS": "10%",
            "MS": "20%",
            "OL": "15%",
            "PP": "20%",
        },
        "spellcaster": False,
    },
}


LANGUAGE_PICK_LIST = [
    "Bugbear",
    "Doppelgänger",
    "Dragon",
    "Dwarvish",
    "Elvish",
    "Gargoyle",
    "Gnoll",
    "Gnomish",
    "Goblin",
    "Halfling",
    "Harpy",
    "Hobgoblin",
    "Kobold",
    "Lizard man",
    "Medusa",
    "Minotaur",
    "Ogre",
    "Orcish",
    "Pixie",
    "Human dialect",
]


MU_ELF_SPELLS_L1 = [
    "Charm Person",
    "Detect Magic",
    "Floating Disc",
    "Hold Portal",
    "Light",
    "Magic Missile",
    "Protection from Evil",
    "Read Languages",
    "Read Magic",
    "Shield",
    "Sleep",
    "Ventriloquism",
]
